-- Autogenerated by Luapress v3.3
-- For available configuation options, see: fizzadar.com/luapress
-- Or see the default config at:
-- github.com/Fizzadar/Luapress/blob/develop/luapress/default_config.lua

local config = {
    title = "Gage K. Peterson",
    url = '',

    force_index_page = true,
    index_page = 'Home',
    archive_title = 'Blog',
    build_dir = 'public_html',

    envs = {
        public = {
            url = 'http://justgage.github.io',
            build_dir = 'public_html',
        }
    }
}

return config
